/* Generated by reswrap version 3.1.0 */

/* created by reswrap from file continue.gif */
extern const unsigned char continue_gif[];

/* created by reswrap from file icon16.gif */
extern const unsigned char icon16_gif[];

/* created by reswrap from file icon32.gif */
extern const unsigned char icon32_gif[];

/* created by reswrap from file pause.gif */
extern const unsigned char pause_gif[];

/* created by reswrap from file pc00.gif */
extern const unsigned char pc00_gif[];

/* created by reswrap from file pc01.gif */
extern const unsigned char pc01_gif[];

/* created by reswrap from file pc02.gif */
extern const unsigned char pc02_gif[];

/* created by reswrap from file pc03.gif */
extern const unsigned char pc03_gif[];

/* created by reswrap from file pc04s.gif */
extern const unsigned char pc04s_gif[];

/* created by reswrap from file .gif */
extern const unsigned char updIcon_gif[];

/* created by reswrap from file play.gif */
extern const unsigned char play_gif[];

/* created by reswrap from file stop.gif */
extern const unsigned char stop_gif[];

/* created by reswrap from file swap.gif */
extern const unsigned char swap_gif[];

/* created by reswrap from file time.gif */
extern const unsigned char time_gif[];

/* created by reswrap from file delbtn.gif */
extern const unsigned char delbtn_gif[];

/* created by reswrap from file emplogbtn.gif */
extern const unsigned char emplogbtn_gif[];

/* created by reswrap from file msgbtn.gif */
extern const unsigned char msgbtn_gif[];

/* created by reswrap from file newbtn.gif */
extern const unsigned char newbtn_gif[];

/* created by reswrap from file flat3dbluebutton_10mins.gif */
extern const unsigned char min10btn_gif[];

/* created by reswrap from file flat3dbluebutton_20min.gif */
extern const unsigned char min20btn_gif[];

/* created by reswrap from file flat3dbluebutton_30min.gif */
extern const unsigned char min30btn_gif[];

/* created by reswrap from file flat3dbluebutton_1hr.gif */
extern const unsigned char min60btn_gif[];

/* created by reswrap from file flat3dbluebutton_1hr.gif */
extern const unsigned char minemptybtn_gif[];

/* created by reswrap from file mkahawa-settings-btn.gif */
extern const unsigned char cyber_settings_gif[];

extern const unsigned char dbutton01_gif[];
extern const unsigned char dbutton0_gif[];
extern const unsigned char dbutton1_gif[];
extern const unsigned char dbutton2_gif[];
extern const unsigned char dbutton3_gif[];
