/* Generated by reswrap version 3.1.0 */

/* created by reswrap from file grabber.gif */
extern const unsigned char grabber_gif[];

/* created by reswrap from file lockscreen.gif */
extern const unsigned char lockscreen_gif[];

